#!/usr/bin/env bash
# Idempotent Cloud Agent setup for the GHRC (Assignment) Android app.
# Safe to run repeatedly: it installs the Android SDK only when missing,
# regenerates local config, and warms the Gradle build cache.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

export ANDROID_HOME="${ANDROID_HOME:-$HOME/android-sdk}"
CMDLINE_TOOLS_VERSION="11076708"
PLATFORM="platforms;android-36"
BUILD_TOOLS="build-tools;36.0.0"

echo "==> Ensuring Android SDK is present at $ANDROID_HOME"
SDKMANAGER="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
if [ ! -x "$SDKMANAGER" ]; then
  echo "    Installing Android command-line tools"
  mkdir -p "$ANDROID_HOME/cmdline-tools"
  tmp_zip="$(mktemp --suffix=.zip)"
  curl -fsSL -o "$tmp_zip" \
    "https://dl.google.com/android/repository/commandlinetools-linux-${CMDLINE_TOOLS_VERSION}_latest.zip"
  rm -rf "$ANDROID_HOME/cmdline-tools/latest" "$ANDROID_HOME/cmdline-tools/cmdline-tools"
  unzip -q "$tmp_zip" -d "$ANDROID_HOME/cmdline-tools"
  mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
  rm -f "$tmp_zip"
fi

echo "==> Accepting SDK licenses"
yes | "$SDKMANAGER" --licenses >/dev/null 2>&1 || true

echo "==> Installing required SDK packages (idempotent)"
"$SDKMANAGER" "platform-tools" "$PLATFORM" "$BUILD_TOOLS" >/dev/null

echo "==> Writing local.properties (sdk.dir)"
printf 'sdk.dir=%s\n' "$ANDROID_HOME" > local.properties

echo "==> Ensuring Supabase secrets file exists"
SECRETS_FILE="app/src/main/java/com/example/assignment/database/SupabaseSecrets.kt"
if [ ! -f "$SECRETS_FILE" ]; then
  # Prefer real credentials from environment secrets when available,
  # otherwise fall back to non-blank placeholders so the project compiles.
  SB_URL="${SUPABASE_URL:-https://placeholder.supabase.co}"
  SB_KEY="${SUPABASE_ANON_KEY:-placeholder-anon-key}"
  cat > "$SECRETS_FILE" <<EOF
package com.example.assignment.database

// Auto-generated by .cursor/install.sh for local/CI builds.
// Real values come from the SUPABASE_URL / SUPABASE_ANON_KEY environment secrets.
object SupabaseSecrets {
    const val url: String = "${SB_URL}"
    const val apiKey: String = "${SB_KEY}"
}
EOF
  echo "    Created $SECRETS_FILE"
else
  echo "    $SECRETS_FILE already present; leaving it untouched"
fi

echo "==> Warming Gradle build (assembleDebug)"
sh ./gradlew :app:assembleDebug --no-daemon

echo "==> Setup complete"
